#!/bin/sh

if [ -f "$1" ]; then
    f="$(readlink -f "$1")"
    case $(file --mime-type -b "$f") in
        application/pdf) setsid -f zathura -- "$f" > /dev/null 2>&1;;
        audio/*|video/*) setsid -f mpv -quiet -- "$f" > /dev/null 2>&1 ;;
        image/x-xcf) setsid -f gimp "$f" >/dev/null 2>&1;;
        image/*) setsid -f feh -. -g 800x600 "$f";;
        text/html) $BROWSER -- "$f";;
        text/*) $EDITOR "$f";;
        *)
            printf "Open with: "
            read -r prog
            [ -n "$prog" ] && "$prog" "$f";;
    esac
fi
