#!/bin/sh
# This file is part of Itsnexn's dotfiles.
#
# Repository: https://github.com/itsnexn/dotfiles
# LICENSE:    MIT (https://opensource.org/licenses/MIT)


xset -dpms &                    # Disable DPMS
xset r rate 300 30 &
setxkbmap -option "ctrl:nocaps" # Capslock => Ctrl
setwall &                       # set wallpaper

autostart="mpd picom wired xbanish"
for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# this fixes the issue with java applications like: arduino-ide and burpsuite
wmname LG3D

# Update xresources
XRESOURCES="${XDG_CONFIG_HOME:-$HOME/.config}/X11/xresources"
[ -f "$XRESOURCES" ] && xrdb "$XRESOURCES"

"$HOME/.config/suckless/dwm/run.sh"
